### ISSUE TITLE
Porting legacy tests from ".Flow/flow" —  test case "should not flow if number of sentinels is less than MIN_FLOW_SENTINELS"  Check relevance.

### ISSUE THREAD

**Issue by Erikd-dev** [rainlanguage/rain.flow#31]
link [should not flow if number of sentinels is less than MIN_FLOW_SENTINELS](https://github.com/rainlanguage/rain-protocol/blob/7f0b708db67001e7dc8122de8a901398ea92a2f3/test/Flow/Flow/flow.ts#L51C7-L51C77)

**Comment by Erikd-dev** [comment]
This test needs to be checked for relevance.
Perhaps I don't fully understand the logic of this test.

**Comment by thedavidmeister** [comment]
@Erikd-dev this test is relevant, if there are missing sentinels that should be an error
