### ISSUE TITLE
Porting legacy tests from ".Flow/context" — test case "should register and load flow times into context (throttle flow output amount)"

### ISSUE THREAD

**Issue by Erikd-dev** [rainlanguage/rain.flow#42]
link [should register and load flow times into context (throttle flow output amount)](https://github.com/rainlanguage/rain-protocol/blob/7f0b708db67001e7dc8122de8a901398ea92a2f3/test/Flow/Flow/context.ts#L45)

**Comment by Erikd-dev** [comment]
In this test use the interpreter and storage are also involved.

The flow ID is set through the context. If the flow is just starting (flow time equals zero), the full amount of tokens is exchanged. 
If the flow continues and less than a day has passed since its start, a reduced amount of tokens is transferred. 
If more than a day has passed since the start of the flow, the full amount of tokens is transferred. At the end of the code, the flow ID is set to the current block time.

If I have correctly understood this test case.

I am considering shortening it to just verify the context transfer to the interpreter.

**Comment by thedavidmeister** [comment]
@Erikd-dev yup sure, just test the context handling directly
