### ISSUE TITLE
Porting legacy tests from ".Flow/context" — test case "should register and load flow times into context (canFlow if no registered flow)"

### ISSUE THREAD

**Issue by Erikd-dev** [rainlanguage/rain.flow#43]
link [should register and load flow times into context (canFlow if no registered flow)](https://github.com/rainlanguage/rain-protocol/blob/7f0b708db67001e7dc8122de8a901398ea92a2f3/test/Flow/Flow/context.ts#L373)

**Comment by Erikd-dev** [comment]
This test needs to be checked for relevance.

**Comment by thedavidmeister** [comment]
@Erikd-dev doesn't seem directly relevant, assuming we have test coverage for both setting state and ensure separately
